-- 008_unified_volumetric_optimization.sql
BEGIN;

-- 1. Consolidated Spatial Racks
-- Merge Zone data into Racks and standardize the 10-rack layout
ALTER TABLE racks
ADD COLUMN IF NOT EXISTS position_x INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS position_y INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS width INTEGER NOT NULL DEFAULT 200,
ADD COLUMN IF NOT EXISTS height INTEGER NOT NULL DEFAULT 150,
ADD COLUMN IF NOT EXISTS color VARCHAR(7) NOT NULL DEFAULT '#2563EB';

-- Remove legacy Zone link
ALTER TABLE racks DROP COLUMN IF EXISTS zone_id;
ALTER TABLE racks DROP COLUMN IF EXISTS position_in_zone;
DROP TABLE IF EXISTS zones CASCADE;

-- 2. Volumetric Storage Cells (4x10 Grid Standards)
ALTER TABLE shelf_slots
DROP COLUMN IF EXISTS capacity,
ADD COLUMN IF NOT EXISTS row_number INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS column_number INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS width_m DECIMAL(10,2) NOT NULL DEFAULT 2.9,
ADD COLUMN IF NOT EXISTS depth_m DECIMAL(10,2) NOT NULL DEFAULT 1.1,
ADD COLUMN IF NOT EXISTS height_m DECIMAL(10,2) NOT NULL DEFAULT 6.0,
ADD COLUMN IF NOT EXISTS max_volume_m3 DECIMAL(10,2) NOT NULL DEFAULT 19.14,
ADD COLUMN IF NOT EXISTS current_volume_m3 DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
ADD COLUMN IF NOT EXISTS max_weight_kg DECIMAL(10,2) NOT NULL DEFAULT 2000.00,
ADD COLUMN IF NOT EXISTS current_weight_kg DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS measured_weight_kg DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS weight_discrepancy_threshold DECIMAL(10,2) NOT NULL DEFAULT 5.00;

-- 3. Advanced Item Metadata
ALTER TABLE items
ADD COLUMN IF NOT EXISTS volume_m3 DECIMAL(10,4) DEFAULT 0.1000,
ADD COLUMN IF NOT EXISTS turnover_class VARCHAR(1) DEFAULT 'C',
ADD COLUMN IF NOT EXISTS is_stackable BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS delivery_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS production_priority INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS next_machine_id UUID REFERENCES machines(id) ON DELETE SET NULL;

COMMIT;
